/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, TouchableOpacity, View} from 'react-native';
import SunmiPrinter from 'react-native-sunmi-printer';

export default class App extends Component<{}> {
  state = {
    loading: false,
  };
  componentDidMount() {}
  handlePrint() {
    if (Platform.OS === 'ios') {
      return;
    }
    SunmiPrinter.connect()
      .then(() => {
        SunmiPrinter.openPrinter({
          printerStyle: {
            // LEFT_SPACING: 50,
            // TEXT_RIGHT_SPACING: 50,
          },
          content: [
            {
              row: [
                {
                  text: 'xx公司',
                  align: 1,
                  fontSize: 40,
                  bold: true,
                },
              ],
              wrap: 1,
            },
            {
              row: [
                {
                  text: '付款号：0053',
                  align: 0,
                  fontSize: 22,
                },
              ],
            },
            {
              row: [
                {
                  text: '收银员：李三',
                  align: 0,
                  fontSize: 22,
                },
              ],
            },
            {
              row: [
                {
                  text: '收银时间：2020-12-21 17:00:00',
                  align: 0,
                  fontSize: 22,
                },
              ],
            },
            {
              row: [
                {
                  text: '支付方式：现金',
                  align: 0,
                  fontSize: 22,
                },
              ],
            },
            {
              row: [
                {
                  text: '==================================',
                  align: 0,
                  fontSize: 22,
                },
              ],
            },
            {
              row: [
                {
                  text: '商品名称',
                  align: 0,
                  width: 2,
                },
                {
                  text: '数量（件）',
                  align: 2,
                  width: 1,
                },
              ],
              fontSize: 22,
              bold: true,
            },
            {
              row: [
                {
                  text: '----------------------------------',
                },
              ],
            },
            {
              row: [
                {
                  text: '品种1 我的名称很长',
                  align: 0,
                  width: 2,
                },
                {
                  text: '1',
                  align: 2,
                  width: 1,
                },
              ],
              fontSize: 22,
              bold: false,
            },
            {
              row: [
                {
                  text: 'xx火龙果一级大果',
                  align: 0,
                  width: 2,
                },
                {
                  text: '19',
                  align: 2,
                  width: 1,
                },
              ],
              fontSize: 22,
              bold: false,
            },
            {
              row: [
                {
                  text: '----------------------------------',
                },
              ],
            },
            {
              row: [
                {
                  text: '合计',
                  align: 0,
                  width: 2,
                },
                {
                  text: '20',
                  align: 2,
                  width: 1,
                },
              ],
              fontSize: 26,
              bold: true,
            },
            {
              row: [
                {
                  text: '----------------------------------',
                  fontSize: 22,
                  bold: false,
                },
              ],
            },
            {
              row: [
                {
                  text: '欢迎再次光临，感谢惠顾！',
                  align: 1,
                  fontSize: 24,
                  bold: false,
                },
              ],
              wrap: 3,
            },
          ],
        });
      })
      .catch(err => {
        console.log(err);
      });
  }
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.handlePrint}>
          <Text>Print</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
